#!/bin/sh

TIMEOUT=1
RETRIES=15
QUIET=0
WGET=0

echoerr() {
  if [ "$QUIET" -ne 1 ]; then printf "%s\n" "$*" 1>&2; fi
}

usage() {
  exitcode="$1"
  cat << USAGE >&2
Usage:
  $cmdname host:port [-t timeout] [-- command args]
  -q | --quiet                        Do not output any status messages
  -w | --wget                         Use wget instead of netcat
  -t TIMEOUT | --timeout=timeout      Timeout in seconds (default 1).
  -r RETRIES | --retries=retries      How many times to retry connection, zero for infinity (default 15).
  -- COMMAND ARGS                     Execute command with args after the test finishes
USAGE
  exit "$exitcode"
}

wait_for() {
  command="$*"
  result=1
  for i in `seq $RETRIES` ; do
    if [ "$WGET" -ne 1 ]; then
      nc -z "$HOST" "$PORT"
      result=$?
    else
      wget -q -T $TIMEOUT "$HOST:$PORT"
      result=$?
      echoerr "Timed out: $i" >&2
    fi

    if [ $result -eq 0 ] ; then
      if [ -n "$command" ] ; then
        exec $command
      fi
      exit 0
    fi
    sleep $TIMEOUT
  done
  echoerr "Operation timed out" >&2
  exit 1
}

while [ $# -gt 0 ]
do
  case "$1" in
    *:* )
    HOST=$(printf "%s\n" "$1"| cut -d : -f 1)
    PORT=$(printf "%s\n" "$1"| cut -d : -f 2)
    shift 1
    ;;
    -q | --quiet)
    QUIET=1
    shift 1
    ;;
    -w | --wget)
    WGET=1
    shift 1
    ;;
    -t)
    TIMEOUT="$2"
    if [ "$TIMEOUT" = "" ]; then break; fi
    shift 2
    ;;
    -r)
    RETRIES="$2"
    if [ "$RETRIES" = "" ]; then break; fi
    shift 2
    ;;
    --timeout=*)
    TIMEOUT="${1#*=}"
    shift 1
    ;;
    --retries=*)
    RETRIES="${1#*=}"
    shift 1
    ;;
    --)
    shift
    break
    ;;
    --help)
    usage 0
    ;;
    *)
    echoerr "Unknown argument: $1"
    usage 1
    ;;
  esac
done

if [ "$HOST" = "" -o "$PORT" = "" ]; then
  echoerr "Error: you need to provide a host and port to test."
  usage 2
fi

wait_for "$@"
