version: '2'

services:
  robot.db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: example
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
    networks:
      - app

  robot.backend:
    build: backend
    command: ./wait-for robot.db:5432 -- npm run dev
    environment:
      DATABASE_URL: postgres://example:example@robot.db/example
    ports:
      - 9000:9000
    depends_on:
      - robot.db
    networks:
      - app

  robot.frontend:
    build: frontend
    environment:
      ENDPOINT: http://robot.backend:9000/api
    ports:
      - 8000:8000
    networks:
      - app

  robot:
    build: robot
    command: sh -c '/robot/wait-for robot.frontend:8000 -t 5 -r 10 --wget -- robot --outputdir /results /robot'
    environment:
      BROWSER: HeadlessChrome
      SERVER: http://robot.frontend:8000
    volumes:
      - ./robot:/robot:ro
      - ./results/robot:/results:rw
    depends_on:
      - robot.backend
      - robot.frontend
    networks:
      - app

networks:
  app:
